import { breadcrumbs, button, hero } from '../templates/site.mjs';

const crumb = (label, path) => breadcrumbs([{ label: 'Inicio', path: '' }, { label, path }]);
const field = (label, name, value, suffix, options = '') => `<label>${label}<span class="input-line"><input name="${name}" value="${value}" inputmode="decimal" ${options} required><span>${suffix}</span></span></label>`;
const error = '<div class="error" data-error role="alert" tabindex="-1" hidden></div>';
const toolCard = (number, title, text, path, label = 'Abrir calculadora') => `<article class="tool-link"><span class="tool-number">${number}</span><div><h2>${title}</h2><p>${text}</p></div>${button(path, label, true)}</article>`;

export const pages = [
  {
    path: '', h1: 'La tierra justa para cada recipiente', title: 'TierraExacta: calculadora de litros de sustrato', description: 'Calcula litros de tierra para macetas, jardineras y bancales, conviértelos en sacos y reparte mezclas de sustrato.',
    schema: { '@context': 'https://schema.org', '@type': 'WebSite', name: 'TierraExacta', url: 'https://elvaropablo-oss.github.io/tierra-exacta/', inLanguage: 'es-ES' },
    content: `${hero('Geometría para cultivar', 'La tierra justa para cada recipiente', 'Mide por dentro. Calcula el hueco real. Convierte el resultado en sacos y prepara la mezcla sin comprar a ojo.', `${button('litros-maceta/', 'Calcular una maceta')}${button('jardinera-bancal/', 'Medir una jardinera', true)}`)}
      <section class="tool-index"><div class="section-intro"><p class="eyebrow">Ruta de cálculo</p><h2>Del recipiente a la mezcla</h2><p>Cuatro herramientas breves. Puedes usar una sola o pasar el resultado a la siguiente.</p></div><div>${toolCard('01', 'Maceta redonda', 'Cilindro o tronco de cono, con borde libre y volumen ocupado.', 'litros-maceta/')}${toolCard('02', 'Jardinera o bancal', 'Volumen rectangular en litros y metros cúbicos.', 'jardinera-bancal/')}${toolCard('03', 'Sacos y coste', 'Añade margen, redondea sacos y calcula el sobrante.', 'sacos-sustrato/')}${toolCard('04', 'Mezcla por proporciones', 'Convierte una receta porcentual en litros de cada componente.', 'mezcla-sustrato/')}</div></section>
      <section class="field-note"><div><p class="eyebrow">La medida que cambia todo</p><h2>Interior, no exterior</h2></div><p>El grosor de las paredes puede restar varios litros. Mide el hueco que realmente vas a llenar y descuenta el borde libre, el drenaje o un cepellón existente.</p><span aria-hidden="true">⌁</span></section>`
  },
  {
    path: 'herramientas', h1: 'Calculadoras de tierra y sustrato', title: 'Calculadoras de tierra y sustrato | TierraExacta', description: 'Herramientas gratuitas para calcular macetas, jardineras, sacos, coste y proporciones de sustrato.',
    content: `${crumb('Herramientas', 'herramientas/')} ${hero('Cuatro pasos, una compra clara', 'Calculadoras de tierra y sustrato', 'Empieza por la forma de tu recipiente. Después puedes convertir los litros calculados en sacos o en una receta de mezcla.')}
      <section class="tool-index tool-index--plain"><div></div><div>${toolCard('01', 'Litros para una maceta', 'Calcula recipientes cilíndricos y macetas más estrechas en la base.', 'litros-maceta/')}${toolCard('02', 'Tierra para jardinera o bancal', 'Calcula prismas rectangulares y varias unidades iguales.', 'jardinera-bancal/')}${toolCard('03', 'Cuántos sacos comprar', 'Aplica margen y redondea según el formato disponible.', 'sacos-sustrato/')}${toolCard('04', 'Mezclar sustrato', 'Reparte el total entre tres ingredientes que sumen el 100 %.', 'mezcla-sustrato/')}</div></section>`
  },
  {
    path: 'litros-maceta', tool: true, h1: 'Calcula los litros de una maceta redonda', title: 'Calculadora de litros para macetas | TierraExacta', description: 'Calcula cuántos litros de sustrato caben en una maceta cilíndrica o troncocónica usando medidas interiores.',
    content: `${crumb('Maceta redonda', 'litros-maceta/')} ${hero('Calculadora 01', 'Calcula los litros de una maceta redonda', 'Mide los diámetros y la altura por dentro. Si la base es más estrecha, selecciona tronco de cono.')}
      <section class="calculator"><form id="round-form" class="calc-form"><div class="form-header"><span>PLANO / 01</span><h2>Medidas interiores</h2></div><label>Forma<select name="shape"><option value="frustum">Más estrecha en la base</option><option value="cylinder">Cilíndrica</option></select></label><div class="field-pair">${field('Diámetro superior', 'topDiameter', '40', 'cm')}<label data-bottom>Diámetro inferior<span class="input-line"><input name="bottomDiameter" value="30" inputmode="decimal" required><span>cm</span></span></label></div><div class="field-pair">${field('Altura interior', 'height', '30', 'cm')}${field('Borde sin llenar', 'freeboard', '2', 'cm')}</div><div class="field-pair">${field('Número de macetas', 'count', '1', 'uds.', 'inputmode="numeric"')}${field('Drenaje o cepellón', 'deductions', '0', 'L')}</div>${error}<button class="button button--clay" type="submit">Calcular litros</button></form><section id="round-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="explainer"><p class="eyebrow">Cómo leer el resultado</p><h2>Qué debes descontar</h2><div><p><strong>Borde sin llenar:</strong> distancia vertical desde el sustrato hasta el borde. Reduce la altura usada en la fórmula.</p><p><strong>Deducciones:</strong> litros que ya ocupan una capa de drenaje, un depósito o un cepellón. Se restan después.</p></div></article>`
  },
  {
    path: 'jardinera-bancal', tool: true, h1: 'Calcula la tierra para una jardinera o bancal', title: 'Calculadora de tierra para jardineras y bancales | TierraExacta', description: 'Calcula litros y metros cúbicos de tierra para jardineras rectangulares, maceteros y bancales elevados.',
    content: `${crumb('Jardinera o bancal', 'jardinera-bancal/')} ${hero('Calculadora 02', 'Calcula la tierra para una jardinera o bancal', 'Usa largo, ancho y alto interiores. El resultado se muestra en litros y metros cúbicos.')}
      <section class="calculator"><form id="bed-form" class="calc-form"><div class="form-header"><span>PLANO / 02</span><h2>Hueco rectangular</h2></div><div class="field-pair">${field('Largo interior', 'length', '100', 'cm')}${field('Ancho interior', 'width', '40', 'cm')}</div><div class="field-pair">${field('Altura interior', 'height', '35', 'cm')}${field('Borde sin llenar', 'freeboard', '5', 'cm')}</div><div class="field-pair">${field('Número de jardineras', 'count', '1', 'uds.', 'inputmode="numeric"')}${field('Volumen ya ocupado', 'deductions', '0', 'L')}</div>${error}<button class="button button--clay" type="submit">Calcular tierra</button></form><section id="bed-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="explainer"><p class="eyebrow">Para bancales grandes</p><h2>Litros y metros cúbicos</h2><div><p>Mil litros equivalen a un metro cúbico. La herramienta muestra ambas unidades para que puedas comparar sacos, big bags y tierra a granel.</p><p>Si el fondo tiene depósito de agua, patas interiores o relleno que no sea sustrato, estima ese volumen y escríbelo como deducción.</p></div></article>`
  },
  {
    path: 'sacos-sustrato', tool: true, h1: 'Calcula cuántos sacos de sustrato comprar', title: 'Cuántos sacos de tierra necesito | TierraExacta', description: 'Convierte litros necesarios en sacos, añade un margen y calcula volumen comprado, sobrante y coste.',
    content: `${crumb('Sacos de sustrato', 'sacos-sustrato/')} ${hero('Calculadora 03', 'Calcula cuántos sacos de sustrato comprar', 'Introduce el volumen que necesitas y el formato que vende la tienda. El redondeo siempre se hace hacia arriba.')}
      <section class="calculator"><form id="bags-form" class="calc-form"><div class="form-header"><span>LISTA / 03</span><h2>Compra de sustrato</h2></div><div class="field-pair">${field('Litros necesarios', 'requiredLitres', '90', 'L')}${field('Margen adicional', 'reserve', '10', '%')}</div><div class="field-pair">${field('Litros por saco', 'bagSize', '40', 'L')}${field('Precio por saco', 'price', '8,50', '€')}</div>${error}<button class="button button--clay" type="submit">Calcular sacos</button></form><section id="bags-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="explainer"><p class="eyebrow">Un margen visible</p><h2>Por qué se añade reserva</h2><div><p>El sustrato puede asentarse y las medidas nunca son perfectas. Un margen pequeño reduce el riesgo de quedarse corto; puedes ponerlo a cero si ya lo has incluido antes.</p><p>El sobrante se calcula contra el objetivo con margen, para que veas exactamente qué parte de la compra quedaría disponible.</p></div></article>`
  },
  {
    path: 'mezcla-sustrato', tool: true, h1: 'Reparte una mezcla de sustrato por porcentajes', title: 'Calculadora de mezclas de sustrato | TierraExacta', description: 'Convierte una receta de sustrato expresada en porcentajes en litros de cada componente.',
    content: `${crumb('Mezcla de sustrato', 'mezcla-sustrato/')} ${hero('Calculadora 04', 'Reparte una mezcla de sustrato por porcentajes', 'Indica el volumen final y una receta que sume 100 %. Obtendrás los litros exactos de cada parte.')}
      <section class="calculator"><form id="mix-form" class="calc-form"><div class="form-header"><span>RECETA / 04</span><h2>Proporciones por volumen</h2></div>${field('Volumen total', 'totalLitres', '80', 'L')}<div class="mix-fields"><label>Componente 1<input name="name1" value="Sustrato universal" required></label>${field('Porcentaje', 'percentage1', '60', '%')}<label>Componente 2<input name="name2" value="Compost" required></label>${field('Porcentaje', 'percentage2', '25', '%')}<label>Componente 3<input name="name3" value="Perlita" required></label>${field('Porcentaje', 'percentage3', '15', '%')}</div>${error}<button class="button button--clay" type="submit">Repartir mezcla</button></form><section id="mix-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="explainer"><p class="eyebrow">Una calculadora, no una receta</p><h2>Adapta los componentes</h2><div><p>Los nombres y porcentajes iniciales solo sirven de ejemplo. Sustitúyelos por la receta adecuada para tu planta y los materiales disponibles.</p><p>Mide todos los ingredientes con el mismo recipiente. La herramienta reparte volumen, no peso.</p></div></article>`
  },
  {
    path: 'guias/medir-maceta', h1: 'Cómo medir una maceta por dentro', title: 'Cómo medir una maceta para calcular sus litros | TierraExacta', description: 'Aprende a medir diámetros, altura útil, borde libre y elementos que ocupan volumen en una maceta.',
    content: `${crumb('Cómo medir', 'guias/medir-maceta/')} ${hero('Guía de campo', 'Cómo medir una maceta por dentro', 'Una cinta métrica y cuatro datos bastan para evitar el error más frecuente: usar las dimensiones exteriores.')}
      <article class="guide"><ol><li><span>01</span><div><h2>Diámetro superior</h2><p>Mide de pared interior a pared interior, pasando por el centro de la abertura.</p></div></li><li><span>02</span><div><h2>Diámetro inferior</h2><p>Mide la base interior. Si coincide con el superior, puedes usar la opción cilíndrica.</p></div></li><li><span>03</span><div><h2>Altura interior</h2><p>Mide desde el fondo útil hasta el borde. No incluyas patas ni el grosor de la base.</p></div></li><li><span>04</span><div><h2>Borde y ocupaciones</h2><p>Decide cuánto espacio dejarás sin llenar. Estima por separado el drenaje, depósito o cepellón.</p></div></li></ol>${button('litros-maceta/', 'Abrir calculadora')}</article>`
  },
  {
    path: 'metodologia', h1: 'Fórmulas y límites de TierraExacta', title: 'Metodología de cálculo | TierraExacta', description: 'Consulta las fórmulas de volumen para cilindros, troncos de cono, prismas, sacos y mezclas.',
    content: `${crumb('Metodología', 'metodologia/')} ${hero('Cuentas transparentes', 'Fórmulas y límites de TierraExacta', 'Cada resultado se puede repetir con una calculadora corriente. Las medidas lineales entran en centímetros y el volumen sale en litros.')}
      <article class="formula-sheet"><section><span>01</span><h2>Cilindro</h2><p>π × radio² × altura ÷ 1.000</p></section><section><span>02</span><h2>Tronco de cono</h2><p>π × altura × (R² + Rr + r²) ÷ 3 ÷ 1.000</p></section><section><span>03</span><h2>Prisma rectangular</h2><p>largo × ancho × altura ÷ 1.000</p></section><section><span>04</span><h2>Sacos</h2><p>Redondeo superior de litros con margen ÷ litros por saco</p></section><section><span>05</span><h2>Mezcla</h2><p>litros totales × porcentaje ÷ 100</p></section></article>
      <article class="prose"><h2>Límites</h2><p>Los resultados describen formas geométricas regulares. Curvas, depósitos, paredes inclinadas irregulares, compactación y asentamiento introducen diferencias. Usa el cálculo como planificación y conserva un margen razonable.</p></article>`
  },
  {
    path: 'preguntas-frecuentes', h1: 'Preguntas frecuentes sobre tierra y macetas', title: 'Preguntas frecuentes | TierraExacta', description: 'Respuestas sobre litros, medidas interiores, drenaje, márgenes, sacos y mezclas de sustrato.',
    content: `${crumb('Preguntas frecuentes', 'preguntas-frecuentes/')} ${hero('Dudas habituales', 'Preguntas frecuentes sobre tierra y macetas', 'Respuestas breves para interpretar bien el resultado.', '', false)}<article class="faq"><details open><summary>¿Uso medidas exteriores o interiores?</summary><p>Interiores. El cálculo busca el hueco que puede ocupar el sustrato.</p></details><details><summary>¿Una maceta de 40 cm tiene siempre los mismos litros?</summary><p>No. También importan la altura, el diámetro de la base y el borde que dejes sin llenar.</p></details><details><summary>¿El drenaje se mide en centímetros o litros?</summary><p>En la herramienta se descuenta en litros. Puedes estimarlo aparte llenando ese espacio con un recipiente de volumen conocido.</p></details><details><summary>¿Los litros de sustrato equivalen a kilos?</summary><p>No hay una conversión fija. El peso cambia según composición, humedad y compactación.</p></details><details><summary>¿Qué margen debo usar?</summary><p>Depende de la precisión de las medidas y del asentamiento esperado. El 10 % inicial es editable y no pretende ser una regla agronómica.</p></details></article>`
  },
  {
    path: 'sobre', h1: 'Sobre TierraExacta', title: 'Sobre el proyecto | TierraExacta', description: 'Conoce el propósito y el alcance de las calculadoras gratuitas de TierraExacta.',
    content: `${crumb('Sobre', 'sobre/')} ${hero('Medir antes de comprar', 'Sobre TierraExacta', 'Este proyecto convierte dimensiones de recipientes en una lista de compra clara y comprobable.', '', false)}<article class="prose"><h2>Propósito</h2><p>TierraExacta ayuda a reducir compras a ojo y viajes extra a la tienda. Conecta geometría, formatos de saco y recetas por volumen en un flujo gratuito.</p><h2>Alcance</h2><p>No decide qué sustrato necesita una especie ni sustituye el consejo agronómico. Calcula cantidades a partir de los datos que introduces.</p></article>`
  },
  {
    path: 'privacidad', h1: 'Privacidad en TierraExacta', title: 'Privacidad | TierraExacta', description: 'Información sobre cálculo local, almacenamiento y medición de uso en TierraExacta.',
    content: `${crumb('Privacidad', 'privacidad/')} ${hero('Datos mínimos', 'Privacidad en TierraExacta', 'Tus medidas se calculan dentro del navegador y no se envían a un servidor propio.', '', false)}<article class="prose"><h2>Medidas introducidas</h2><p>El último resultado puede guardarse en el almacenamiento local de tu navegador. No se necesita una cuenta y TierraExacta no recibe el contenido de los formularios.</p><h2>Analítica</h2><p>La web utiliza Google Analytics para conocer visitas y uso general mediante el identificador G-EL1YW63SXD. Google puede tratar datos técnicos de navegación según su propia política.</p></article>`
  },
  { path: '404', output: '404.html', noindex: true, h1: 'Página no encontrada', title: 'Página no encontrada | TierraExacta', description: 'La página solicitada no existe.', content: `${hero('Error 404', 'Esta página no ha echado raíces', 'La dirección puede contener un error o haber cambiado.', button('', 'Volver al inicio'), false)}` }
];
